:encoding: UTF-8
// The markup language of this document is AsciiDoc

= C&plus;&plus;

This is about the rules and terms of the C&plus;&plus; programming language. It is my summary of the C&plus;&plus; standard.  Best practices / guidelines are in +programming_practices.txt+ and ++cpp_guidelines.txt++.


== Basic / misc. concepts

=== Undefined behavior

Example where UB is kind of distributed

--------------------------------------------------
long l = ...; // say larger than INT_MAX
for (int i=0;
      i<l; // implicit convertion of i to long
      ++i) // might overlow -> UB
  { /* nop - irrelevant */ }
--------------------------------------------------

- https://stackoverflow.com/questions/367633/what-are-all-the-common-undefined-behaviours-that-a-c-programmer-should-know-a
- http://en.cppreference.com/w/cpp/language/ub
- https://blog.regehr.org/archives/1520[Undefined Behavior in 2017]
- https://www.youtube.com/watch?v=v1COuU2vU_w[CppCon 2017: John Regehr “Undefined Behavior in 2017 (part 1 of 2)”]
- https://www.youtube.com/watch?v=yG1OZ69H_-o&t=1215s[CppCon 2016: Chandler Carruth “Garbage In Garbage Out: Arguing about Undefined Behavior"]
- https://www.youtube.com/watch?v=g7entxbQOCc&t=2340s[CppCon 2016: Michael Spencer “My Little Optimizer: Undefined Behavior is Magic"]
- http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html[What Every C Programmer Should Know About Undefined Behavior #1/3]


=== References

C&plus;&plus;98 references are covered by the `references' koan in cppkoans.

_rvalue references_: C&plus;&plus;11 adds rvalue references.  An rvalue reference can bind to rvalues (e.g. temporaries), thus now we can also modify rvalues (e.g. temporaries) through rvalue references.

_Which reference binds to which value categories_: The following table specifies which expressions can bind to which references. The numbers specify which viable match is better, see overload resolution below.

|===
.2+| syntax .2+| name              4+| can bind to ...
                                     | mut lvalue | immut lvalue | mut rvalue | immut rvalue
| T&&       | rvalue reference       |            |              | y 1  ①    |
| const T&&②| const rvalue reference |            |              | y 2       | y 1
| T&        | lvalue reference       | y 1        |              |            |
| const T&  | const lvalue reference | y 2        | y            | y 3        | y 2
|===

① The one important change in C&plus;&plus;11: Having an rvalue reference which
can bind to a (mutable) rvalue _and modify_ it through the reference.  Using a
const lvalue reference we could already bind to an rvalue before, but we could not
modify it through the reference.

② Const rvalue references are also new, but in general not really useful,
since with const lvalue references we can already bind to rvalues.

_Overload resolution_: Regarding overload resolution, when there are multiple viable references, the rules for which viable match is better: 1) rvalue reference is better than an lvalue reference 2) less cv-qualified is better. The number in the table tells the overload resolution order, 1 means most prefered.

[[forwarding_reference]] _forwarding reference_ (or _universal reference_): A forwarding reference can appear as the type of a template function argument (e.g. "template <class T> void f(T&&);"), or as auto&& (e.g. "auto&& obj = bar();"). A forwarding reference preserves the value category of the function argument / initializer. If an rvalue is passed, the type of the argument / object will be rvalue ref (T&&), if an lvalue is passed, it will be lvalue ref (T&), see also <<template_argument_deduction>> and <<auto_variable_type_deduction>>. *to-do* Item 28 - forwarding references are not a new kind of references, the're really just rvalue references

_Rules for modifying rvalues_: Nothing new. We're never allowed to bring an
object into an invalid state, also not when modifying it through an rvalue
reference. Consider the following example:

--------------------------------------------------
void foo(T&& param) {
  ... /* do anything with param which leaves it in a valid state */
};
...
{
  T obj;
  foo(move(obj)); // move is only an (unconditional) cast to T&&
  // obj is in unspecified (unless foo specifies it) but valid state
} // obj is destructed, i.e. referenced by it's destructor
--------------------------------------------------

foo's modifications must be in a way that leave the object in a valid
state. After all, the caller of foo must at least be able to destruct the object
he passed to foo. The implementation of a method taking an rvalue reference is
almost always to steal the resources of the rvalue parameter. E.g. the vector's
move constructor vector<T>(vector<T>&& rhs) probably is implemented by
overtaking ownership of rhs's underlying dynamically allocated array and then
leave the rhs as being an empty vector. The resources can be stolen because the
caller doesn't care anymore about the content of the object he passed. See also
move, and what promise you make when you use it. Since modifying an rvalue
almost always means stealing resources from it, when passing an object to a
function taking an rvalue reference (e.g. move constructor or move assignment),
we say that we _move from_ the object.

Remember: ``move doesn't move and forward doesn't forward''. move
is an __un__conditional static cast to rvalue. forward is an _conditional_
cast to rvalue. See the following definitions for each.

_std::move_: move is an unconditional static cast to rvalue reference (thus is
an xvalue). It is a promise that you don't care about the object's content
anymore, only that it remains in some valid state. You still can reference / use
the object the normal way. For example, the canonical example for swap is:

------------------------------------------------------------
template<typename T>
void swap(T& a, T&b) {
  T tmp(move(a));
  a = move(b);   // a   is referenced although we already moved from it
  b = move(tmp)  // tmp "  "          "       "  "       "     "    "
} // tmp and a are referenced by their destructor
------------------------------------------------------------

Some sources (even notable ones from the C&plus;&plus; committee) contradict the
previous paragraph. They say that the move in "MyType obj; foo(move(obj));" is a
promise that obj is not referenced after the full expression containing the
move. This statement is based on that in "foo(makeMyType());", the produced
temporary is destructed at the end of the full expression containing it, thus
there is no way that somebody after foo could reference the temporary, and that
move is a promise that the situation is the same as with the temporary.  *to-do*
I don't have any references for my statement. So which of the two paragraphs
(see also the following), is now finally provably correct?

_std::forward_: Being passed a forwarding reference, yields the value category
of the object the forwarding reference was bound to. In other words, forward
casts it's argument, an (const) lvalue, to rvalue reference iff its argument was
initialized to an rvalue, and otherwise leaves it at (const) lvalue
reference. Using forward means making the same promise as using move. For
example: *to-do* clean up the wording *to-do* in the auto example, why does
decltype(bar) play the role of T? In the template case, T is string, but in the
auto case, decltype(bar) is string&&.

--------------------------------------------------
void foo(string&&);
void foo(const string&);
void foo(string&);
template<class T> void wrapper(T&& arg) { foo(forward<T>(arg)); }
...
{
  const string cstr{};
  string str{};

  wrapper(string{});    // param's type is string&&, forward yields the same
                        // Without forward, wrapper would pass an lvalue
                        // and thus call foo(string&)
  wrapper(cstr);        // param's type is const string&, forward yields the same
  wrapper(str);         // param's type is string&, forward yields the same
                        // If wrapper would use move, foo would
                        // move from str without the intent of the
                        // the caller of wrapper

  // same principle with auto, only that in case of rvalues, the template arg to
  // forward is now string&& instead string.
  auto&& bar1 = string{};
  foo(forward<decltype(bar1)>(bar1)); // decltype(bar1) is string&&

  auto&& bar2 = cstr;
  foo(forward<decltype(bar2)>(bar2)); // decltype(bar2) is const string&
}
--------------------------------------------------

[[reference_collapsing]]
_reference collapsing_: In certain situations, e.g. template instantiation, e.g. in <<template_argument_deduction>> with forwarding references, the compiler arrives at a situation where it gets a reference to a reference. Since there's no such thing as a reference to a reference (a reference is not an object), so called reference collapsing occures. It states that the resultinig reference is an rvalue reference iff both references are rvalue references, and lvalue reference otherwise.


=== Initialization

See also cpp_initialization.ods.

C&plus;&plus;11 adds _uniform initialization_ using the brace syntax. Unlike C&plus;&plus;98's different syntaxes of initialization, it an be used anywhere (locals, members, statics etc.) an express anything (e.g. now we also can initialize collections).

--------------------------------------------------
// C++98
rectangle        a(origin(),extends());  // oops, vexing parse
complex<double>  c( 2.71828, 3.14159 );
mystruct         m = { 1, 2 };
int              a[] = { 1, 2, 3, 4 };
vector<int>      v;                              // urk, need more code
for( int i = 1; i <= 4; ++i ) v.push_back(i);    //   to initialize this

// C++11 (note: "=" is mostly optional)
rectangle       w   = {origin(), extents()};
complex<double> c   = {2.71828, 3.14159};
mystruct        m   = {1, 2};
int             a[] = {1, 2, 3, 4};
vector<int>     v   = {1, 2, 3, 4};
--------------------------------------------------

Some uniform initialization rules

- Uniform initialization prohibits narrowing conversions.

- "T foo = bar" (copy initialization) means the same as "T foo(T(bar))" (conversion to T, then copy or move ctor using the temporary).

- "T foo = \{bar}" (copy list initialization) is the almost same as "T foo\{bar}" (direct initialization), only that the former can't use explicit ctors.

- If there is at leas one initializer_list ctor, and using the uniform initialization, it is _strongly_ preferred over other ctors; if there is any way to call it, it will be called. E.g. if a class has a ctor with signature "(int, bool)" and a ctor "(initializer_list<long double>)", the initializer "{10, true}" calls the initializer list constructor by converting the arguments to long double. Say in the previous example the class also has a convertion operator "operator float() const" and a copy ctor and a move ctor. Then, say x is of the class' type, the initializers "\{x}" and "{move(x)}" will both call the initializer list ctor, as opposed to the copy ctor or the move ctor respectively.

- An empty ++{}++ list as initializer calls the default constructor if both the default ctor and the initializer_list ctor are available. If you want to call the initializer_list ctor, use "foo({})".

- <<auto_variable_type_deduction>> has special rules if the initializer is a braced initializer, see there.

Some general initialization rules:

- _Most vexing parse_: The standard says ``If it can be a function declaration, it is.''. Thus both of the following are function declarations, not object definitions: ++T obj();++ and ++T obj(foo(),bar())++, given foo and bar are types. Another reason not to use initializers based on parens.

- _zero initialization_: static T t; T(); T t = {}; T t{}; *to-do* more details https://en.cppreference.com/w/cpp/language/zero_initialization

- _copy initialization_ vs _direct initialization_ *to-do*


References:

- http://herbsutter.com/2013/05/09/gotw-1-solution/

- Book "Effective Modern C&plus;&plus;", Chapter 3


=== Elision / RVO / NRVO

++return _expression_;++: Returning by value may involve construction and
copy/move of a temporary object, unless copy elision is used.  Flori's
abbreviation: if the expression is an lvalue it is tagged to be an rvalue
(*to-do*: xvalue or prvalue ?) so the move constructor or copy constructor
taking reference to const may be taken.
http://en.cppreference.com/w/cpp/language/return


[[type_deduction]]
=== Type deduction

References:

- Type deduction and why you care, by Scott Meyers.
  https://www.youtube.com/watch?v=wQxj20X-tIU[Video],
  https://github.com/CppCon/CppCon2014[Presentation]

- Book "Effective Modern C&plus;&plus;", Chapters 1-4

==== Summary

decltype(id-expression): type the id-expression was declared as +
decltype(expr): expr is of type T: xvalue -> T&&, lvalue -> T&, prvalue -> T

function template argument deduction: The type of the template parameter follows quite naturally from the value category of the function call argument. Say our arguments are ints. lvalue -> int& or const int&, const lvalue -> const int&, rvalue -> const int& or int&&. The type the the template argument (T in the examples here) follows naturally from the parameter type. Only if the template parameter is T&& (forwarding reference), knowing the type of T is a bit more involved.

The other forms of type deduction (_TD_) are based on decltype or function template argument deduction (_FTAD_):

|=====
|auto variable TD                      | FTAD with exceptions: +
...auto... obj = {...}; -> deduced type is initializer_list +
...auto... obj\{expr}; -> deduced type is FTAD on expr
|auto function return TD            .2+| FTAD
|auto parameter TD
|decltype(auto) variable TD         .3+| decltype
|decltype(auto) function return TD
|decltype(auto) parameter TD
|=====



[[decltype]]
==== decltype

decltype(...) yields the type of it's argument.

case decltype(http://www.nongnu.org/hcb/#id-expression[id-expression]): Yields the type the id-expression was declared as.

case decltype(expr): The type yielded by decltype depends on the value category of expr. Say expr is of type T. xvalue -> T&&, lvalue -> T&, prvalue -> T. Recall that a brace-init-list is not an expression. It thus can't be passed and it also woudn't have a type.

--------------------------------------------------
int i{};
int& ri = i;
//                   yields    argument
// decltype(ri)      int&      id-expression
// decltype((ri))    int       expr
// decltype(ri+1)    int       expr
// decltype({i,41})  compile error
--------------------------------------------------


[[template_argument_deduction]]
==== Function template argument deduction

_Template argument deduction_ (or _function template type deduction_ or _template type deduction_ (since C&plus;&plus;98) deduces the template argument in case a template function call doesn't explicitely specify it. E.g. in "template<class T> void f(T); f(42);" the call doesn't specify the template argument. "f<int>(42);" is an example were the template argument is specified. The following table specifies how the type deduction works, given the value category of the function call argument:

--------------------------------------------------
int i{42};
const int ci{42};
--------------------------------------------------

|=====
.3+| argument's value category .3+| example 8+| parameter declaration in template<class T> void f(...)
                     2+| T                2+| T& ②                  2+| const T& ②      2+| T&&
                       | T   | param's type | T         | param's type | T   | param's type | T          | param's type
| lvalue       | f(i)  | int | int          | int       | int&         | int | const int&   | int& ③    | int& ④
| const lvalue | f(ci) | int | int ①       | const int | const int&   | int | const int&   | const int& | const int&
| rvalue       | f(42) | int | int        2+| compile error ⑤         | int | const int&   | int ③     | int&&
|              | f({i, 42}) 8+| compile error ⑥
|=====

The rules are quite natural.

- Parameter declaration is of non reference type (T): The deduced parameter type equals the argument type.

- Parameter declaration is of reference type (T&, const T&, T&&): The deduced parameter type is kind of the `natural' intersection bewteen what you asked for (T&, const T&, or T&&) and the value type of the argument. Const is never dropped but possibly added, rvalues can bind to T&& and const T& but not to T&. *to-do* find a more elegant / concise way of phrasing it.

① const is dropped since the parameter is an independent object.

② Analogous rules for pointers (i.e. "f(T*)" and "f(const T*)").

③ This makes std::forward work, since now from the type of T one can deduce whether the value bound to the parameter was an lvalue (T is of reference type) or an rvalue (T is of non-reference type).

④ Naively, since T is int& and the parameter declaration is T&&, the parameter type ought to be the nonsensical T& &&. However the rules of <<reference_collapsing>> dictate that the actual resulting parameter type is T&.

⑤ Can't bind rvalue to (non-const) lvalue.

⑥ A brace-init-list is not an expression and thus doesn't has a type. Template type deduction (in contrast to variable type deduction) doesn't try to come up with a type, and a program that tries to do so is ill-formed. Thus "template<class T> void f(T); f({1,2})" is ill-formed. *to-do* however it works if the template parameter decl is initializer_list<U>

Recall that:

- Temporary objects are (non-const) rvalues, and that there are no const rvalues
  (*to-do* make sure the latter statement is really true).

- After declaring a reference, e.g. "int& ri = i;", the expression "ri" in
  almost all cases means the referee, and thus is of type int, not int&.


Caveats, all of which are related to decaying types. The bottom line is that there is nothing special. Passing arrays or functions by values does not exist, thus in such a case the array and function respectively decays. After the decay, the normal rules apply.

- If an array is passed (e.g. "int a[42]; f(a)"):

  * Param type is "T": deduced type is "int*". The array decays to "int*" and from there the normal type deduction rules apply. Recall that there is no such thing as passing an array by value. "void f(int a[])" is exactly the same as "void f(int*a)".

  * Param type is "T&" (or with pointer and/or const qualified): deduced type is "int(&)[42]". I.e. array does not decay and we have the regular rules.

- Analalgous rules apply for passing functions


[[auto_variable_type_deduction]]
==== auto / decltype(auto) variable type deduction

Added in C&plus;&plus;11. Works by definition, with exceptions related to braced initializer, the same as function template type deduction. As the following table shows, for each an variable declared with auto there's by definition an imaginary template function declaration. The type in the template parameter declaration is constructed from the type in the auto declaration by replacing every occurence of auto by U. Auto variable type deduction yields by definition the same type as function template type deduction on that imaginary template.

|======
| auto variable type deduction         | equivalent function template type deduction

| ...auto... foo = expr;  +
  ...auto... foo(expr); +
  ...auto... foo\{expr};①             | template<typename U> +
                                         void f(...U...); +
                                         f(expr);

| exception in case of copy-list-initialization: +
  ...auto... foo = {...};              | template<typename U> +
                                         void f(...initializer_list<U>...); +
                                         f({...});
|======

① In case of direct-list-initialization, the braced initializer must contain exactly one element. That direct-list-initialization works as normal was added by N3922, a defect of C&plus;&plus;14. Without N3922, direct-list-initialization works as copy-list-initialization.


_decltype(auto)_ (added in C&plus;&plus14) works exactly the same as decltype. Say the definition is "decltype(auto) foo = expr;", then the deduced type is whatever decltype(expr) yields. what decltype(auto) cannot be combined with other type specifiers. *to-do* reminder to use forward


==== auto / decltype(auto) function return type deduction

Works by definition the same as function template deduction. E.g. say the function is "...auto... foo() { return expr; }", then the type deduced is as "template<typename ...U...> void f(U); f(expr)" does it. If the function has multiple return statements, all types must exactly agree *to-do* is this really correct that they must exactly agree?

_decltype(auto)_ (added in C&plus;&plus;14) works exactly the same as decltype. Say the function is "decltype(auto) f() { return expr; }", then the type of the function is whatever decltype(expr) yields. decltype(auto) cannot be combined with other type specifiers.


==== auto parameter type deduction (in lambdas)

Works by definition the same as function template deduction. E.g. "[](...auto..., ...auto...)void {...}" is conceptually translated to "template<class T1, class T2> void f(...T1... ,...T2...)".


=== Structured bindings


Why, if "auto [...] = ..." means, as a first step, making an unnamed local like "auto unnamed = ...", structured bindings work with arrays? Since accoding to type deduction rules, if the initializer is of type array of T, it decays to T*. May that initial statement was only a good analogy, not the 100% exact thing, and/or there's an exception for auto and arrays in the context of structured bindings.


== Expressions

An _object_ is a region of storage (simplified). Don't confuse with notion of
class object.  Functions (although it often occupies storage), references,
classes and other types, namespaces, enumerators, and templates are not
objects.  Std [intro.object] ... An object is created by a definition (3.1),
by a new-expression (5.3.4) or by the implementation (12.2) when needed.  ...

An _expression_ is a sequence of operators and their operands.  The operands
of any operator may be other expressions or primary expressions.  Each
expression has some non-reference type, and each expression belongs to exactly
one of the tree primary value categories.  _Literals_ and _identifiers_ are
primary expressions.

=== Value categories

Primary value categories:

_lvalue_: A non-temporary object or a non-member function.  Properties: Those of
glvalue, plus address may be taken, can be lhs operand of built-in assignment
operator unless non-modifiable, may be used to initialize an non-const lvalue
reference.  Note that an lvalue can be non-modifiable. Examples for lvalues
which don't have a name: literal string, objects on heap, array elements

_prvalue_ (pure rvalue): A temporary object or a value that is not an object.
Properties: those of rvalue, cannot be polymorphic, a non-class prvalue cannot
be cv-qualified, cannot have incomplete type. *to-do* examples for values which
are not objects. Literals?

_xvalue_: Simplified: Things whose return type is an rvalue reference.
Properties: those of rvalue, those of glvalue. IMHO saying it's about an
eXpiring object is misleading, since that also applies to rvalues in general.

Mixed value categories:

_glvalue_ (generalized lvalue): Properties: May be polymorphic and a few more.

_rvalue_: Properties: Can be used to initialize a const lvalue reference or a
rvalue reference (the latter is the major new feature of C&plus;&plus;11),
address can't be taken (although we can initialize references to it), can't be
used as lhs of the built-in assignment operator (however it can be the lhs of an
overloaded assignment operator).

----------------------------------------------------------------------
                                 C++11
                                   | As Venn diagram
         i !m     i m      !i  m   |     __________ ___________
primary: lvalue   xvalue   prvalue |    /           X           \
             \     /   \    /      |   /           / \           \
mixed:       glvalue   rvalue      |  |   lvalue  | x |  prvalue  |
             i         m           |   \  (part)   \ /   (part)  /
                                   |    \___________X___________/
legend: i: has identity            |     glvalue          rvalue
        m: movable                 |     (whole)          (whole)
-----------------------------------+----------------------------------
                                 C++98  _______      ________
         lvalue        rvalue      |   /        \   /        \
                                   |  |  lvalue  | |  rvalue  |
                                   |   \________/   \________/
----------------------------------------------------------------------

The only really new value category C&plus;&plus;11 introduced is xvalues. The
`new' mixed value categories glvalue and prvalue are only to name different
`new' regions of the Venn diagram which emerged due to the introduction of
xvalues.  xvalues in turn were added as a consequence of the addition of rvalue
references.

The same information the description of primary / mixed value catgories already
presented, are here redundantly presented other way round: Which expressions
have which value type:

|===
| Literal string                                                 | lvalue
| Function                                                       | lvalue (*to-do*: but it is not an object, how does that fit together?)
| Cast to rvalu                                                  | lvalue
| Variable                                                       | lvalue
| Lambda                                                         | prvalue
| Literal, not string                                            | prvalue
| Function call or cast where returned type is an lvalue reference  | lvalue
| Function call or cast where returned type is not a reference  | prvalue
| Function call or cast where returned type is an rvalue reference to object type  | xvalue
| builtin operators: pre inc/dec, dereference, (compound) assignment, subscript (except on array xvalue), comma when if the rhs is lvalue, ternary if 2nd and 3rd are lvalues, ... (*to-do*) member stuff | lvalue
| builtin operators: post inc/dec, arithmetic, logical, comparison, address-of, comma when rhs is rvalue, ternary when either 2nd or 3rd is not lvalue, ... (*to-do* member stuff) | prvalue
| ... (*to-do*: member stuff) | xvalue
|===

References:

- http://stackoverflow.com/questions/3601602/what-are-rvalues-lvalues-xvalues-glvalues-and-prvalues
- <<TCppPL>> Chapter 6.4
- <<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3055.pdf,n3055 >>
- http://en.cppreference.com/w/cpp/language/value_category


== Resources

- Collection of resources on modern C&plus;&plus;: https://github.com/rigtorp/awesome-modern-cpp

- online compiler (gcc, clang,...) to inspect produced assembly: https://godbolt.org/. Tooltips for the machine instructions.

- online micro benchmark: http://quick-bench.com

- Hyperlinked C++ BNF Grammar: http://www.nongnu.org/hcb/

- Webpage: The Definitive C&plus;&plus; Book Guide and List: https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list

- Webpage: Top mentioned books on stackoverflow.com: http://www.dev-books.com/


== Bibliography

- [[[TCppPL]]] The C&plus;&plus; programming language, 4rd edition.

//  LocalWords:  TCppPL eXpiring rvalues xvalues prvalues pre dec Flori
