:encoding: UTF-8
// The markup language of this document is AsciiDoc

= Git

== Inspection

Contents of a file at a certain revision::
  ++git show++. Alternatively use ++git checkout++ and you'll have the files in
  your working directory.

Human digestable name of a revision::
  ++git name-rev++, ++git describe++

Diff of two revisions::
  ++git diff++

Commit logs::
  ++git log++ (++git-rev-list++ as the low level alternative from the plumbing section).

Status of working tree and staging area::
  ++git status++

== Transitions

The following copy files between the following three participants: the working
tree, the index aka the staging area and the repository.

.Working tree -> index, aka stage
- all (modified, new, deleted): ++git add -A++
- single files: ++git add <pathspec>...++

.Working tree -> index and new commit in repository, aka commit -a
I.e. additionally HEAD is modified.
Its not possible to only copy to repository but not also to index.
- all (which are also in index): ++git commit -a++
- single files (which must also be in index): ++git commit <file>...++

.Remove from working tree
- single files: ++/bin/rm <file>...++
- untracked files: ++git clean -n++ to test, ++git clean -f++ to actually unrecoverably do it, ++git clean -i++ to interactively select files to be removed, or trash them with ++git ls-files --others --exclude-standard -z | xargs -0 trash ++

.Index -> new commit in repository, aka commit
I.e. additionally HEAD is modified
- all: ++git commit++

.Index -> Working tree, aka discard-to-index
- all: ++git checkout-index -a++
- single files: ++git checkout-index <file>...++

.Remove from Index
- single files: ++git rm --cache <file>...++

.Current commit -> index, aka unstage
- all: ??
- single files: ++git reset -- <file>...++

.Repository -> working tree, aka discard(-to-HEAD)
- all: ++git checkout -- .++  !!!! really ??? only when exec from repo root ???
- single files: ++git checkout -- <file>...++

.Remove from repository
Fortunately not directly possible.  When commits, or git objects in general,
become unreachable, eventually they will be pruned by the garbage collector.


== Tags

git fetch
- by default, any tag that points to the history of a fetched ref is also fetched. *to-do*: what if a tag with that name already exists locally? The effect seems not to be explainaible with a refspec analogy, because local tags are _never_ updated.
- --tags: in addition (changed in git 1.9, before it was not 'in additon') to what otherwise would be fetched, fetch all tags from remote. *to-do*: apparently that does update local tags, even if not fast forward. It seems the effect is like _adding_ the refspec  ++++refs/tags/*:refs/tags/*+++.
- --no-tags: do not automatically fetch tags pointing to the history of fetched refs.
- --prune: regarding tags, only has an effect if tags are fetched due to an explicit refspe (command line or in remote config).
- -f, --force: When git fetch is used with <rbranch>:<lbranch> refspec, it refuses to update the local branch <lbranch> unless the remote branch <rbranch> it fetches is a descendant of <lbranch>. This option overrides that check. *to-do*: it seems that this does not apply to tags implicitely fetched in the `default mode' (i.e. neither --tags nor --no-tags specified). Thus that adds a leading \+ to every refspec?
- refspec: leading +: "the local ref is updated even if it does not result in a fast-forward update"

about updating existing local tags:

- never update: what the `default' behaviour does, i.e. when neither --tags nor --no-tags is given
- only update if it's a fast forward: your refspec without leading \+ and no --force option.
- always update: + prefix to refspec, --force option. Note that --tags seems to be equivalent to _adding_ refspec ++++refs/tags/*:refs/tags/*+++.

remote.<name>.tagOpt: Either --no-tags or --tags, i.e. the option passed to fetch.

git pull by
- default does not push tags?
- option --tags tells to push all refs under refs/tags, in addition to
  refspecs explicitly listed on the command line.
- push.followTags / options --follow-tags / --no-follow-tags (undocumented in
  git push, but in git config). In addition to what would otherwise be pushed,
  also push annotated tags pointing at commit-ish that are reachable from the
  refs being pushed.


== Patches

.create with diff
- from commit:
- from commit range: ++git format-patch <since>++
- from working tree: ++git diff >foo.patch++
- from index: ++git diff --cached >foo.patch++

.apply
- ++git am -3 foo.patch++
- ++git apply -3 foo.patch++


== Undo Mistakes
In addition to what is under chapter transitions.

++git revert++:: Add a new commit which undoes the given commit
++git reset++::
++git commit --amend++::
++git checkout -f++:: Throw away local changes
++git rebase --interactive++::
++git filter-branch++::


== Questions

What's the difference between ++git log++ and ++git rev-list++?::
  They are mostly the same. log is from the porcelain layer, rev-list from
  plumbing, thus rev-list is seldom used. There are only a few things rev-log
  can do which log can't. See also
  http://www.amailbox.org/mailarchive/git/2008/5/30/1983864/.

Refspec for fetch::
  Note that the fully qualified name for local branches is refs/heads/<name>, and for remote tracking branches its refs/remotes/<remote-name>/<name>. See also SPECIFYING REVISIONS in git-rev-parse(1). Thus fetching only some branches results in e.g. (`refs' already left away) ++fetch origin R8.0:remotes/origin/R8.0 R9.1:remotes/origin/R9.1++. Still, why does it now I don't mean a local branch FQN 'refs/remotes/origin/R9.1`? It `missinterprets' ++fetch origin R9.1:origin/R9.1++ and ++fetch origin R9.1:R9.1++. The more basic Question maybe is: what are the rules as in SPECIFYING REVISIONS in git-rev-parse(1) when creating (opposed to lookup) a ref name?


- What happens with the `branch name/reference' after merging?
- Where is the beginning of a branch, i.e. up to where does ++git branch -d++
  delete? Possibly the commit given when the branch was created?
- What's the difference between a reamote branch and a branch. Why is it `only'
  remote? I made a clone, didn't I?
- upstream branch?
- From http://stackoverflow.com/questions/67699/how-do-i-clone-all-remote-branches-with-git
+
----------------------------------------------------------------------
If you just want to take a quick peek at an upstream branch, you can check it out directly:
$ git checkout origin/experimental
But if you want to work on that branch, you'll need to create a local tracking branch:
$ git checkout -b experimental origin/experimental
----------------------------------------------------------------------
+
Why is the first checkout not good enough? what happens if i do git commit there?

- difference ++git reset++ +--hard+/+--soft+. Now does both completely remove
  commits or not? Or is a new commit created which undoes the unwanted commits?
- `You can check out those (remote) branches like a normal branch, but you should
  not change them.' So, what would happen?
- what exactly does ++git branch -d++ delete? Only the reference, or also commits?
- difference revision - commit? Add to terms
- What's the difference between ++git describe++ and ++git name-rev++?


== Tune rename heuristics

git diff --summary -M10% <commit> <commit> -- <path>...

git cherry-pick --strategy="recursive" --strategy-option="rename-threshold=10%" <commit>...

git config merge.renameLimit 99999999
...
git config --unset merge.renameLimit


== Submodules

gitlink: +git add path+ (without trailing slash), path being top-level directory of a git repository. Seems to work without respective  .gitmodules or .git/config config. Also subsequent commit, and later checkout of that commit.

git clone (non recursive) creates the dirs of submodules, but does nothing more than that, i.e. it does not clone/checkout them.

Superproject has socalled `gitlink' tree entries in its trees (commit and
index). A gitlink refers to a particular commit obj in the inner
repository. Mode (as reported by git status) of a gitlink entry is
160000. Gitlinks are allowed to refer inexistent commit objects (see also
`registred submodule'). This allows for partial checkouts, i.e. not checking
out submodules one doesn't need.

+++git add+++ automatically creates a gitlink if a path argument is a directory (_without_ trailing slash) being the top-level directory of a git project. It really only does that and nothing else, say related to .gitmodules, .git/config, .git/modules.

The +++.gitmodules+++ file in the superproject's top-level directory mainly
defines +path+ and +url+. +path+ is the relativ path within the superprojects
tree where the submodule's tree is placed in. +url+ is the submodudle's url,
i.e. from where the submodule can be cloned. To be precise, it's the
`official' url from the point of view of the superproject. You can always
personalize it by modifying the url in your git config file (probably the
repository related one).

++submodule init++: Of those submodules having an gitlink entry in the index,
copy respective configurations from .gitmodules to .git/config. git-config(1)
says: submodule.<name>.url: ... After obtaining the submodule, the presence of
this variable is used as a sign whether the submodule is of interest to git
commands.

++submodule update++ `updates' the working tree of _registered_ submodules
(i.e. the ones in .git/config?) to match what the superproject expects. That
includes cloning if neccessairy. There are several supported update
procedures: `checkout', `rebase', `merge', `custom command', `none'.

++submodule init; ...; submodule update++ vs ++submodule update --init++. The
former is intended for the case where you want to customize submodule related
config in .git/config.

++git submodule add [--name <name>] <url> [<path>]++: <name> is the logical name of the suprepo; it's probably seldom used. Adds given information to a new submodule.<name> section to .gitmodules and .git/config. If <path> does not already exist, clones from <url> and makes <path>/.git refer to a newly created directory .git/modules/<name>. Adds a gitlink at <path> to the index, pointing to the current commit of the repo at <path>. If not given, <name> and <path> are deduced: <path> from <url>, and <name> from <path>. Aborts if <path> exists but is not a valid Git repo (includes an empty directory), or if index already contains <path>, or if .git/modules/<name> already exits. Note that it silently overwrites submodule.<name>.url if it already exits in .git/config. Note that if there is already a valid Git repo at <path>, <url> is only used for the added content to .gitmodules. Note that submodule add also incorporates what submodule init does.

++git submodule deinit <path>++ Maps <path> to <name> using .gitmodules in the index, removes the whole submodule.<name> section from .git/config (i.e. customizations are lost! (*to-do* is that what the active configuration is meant for?)), and removes all files from <path>, including ignored files! The <path> entry in the index, the submodule.<name> section in .gitmodules, and .git/modules/<name> remain unaffected. Aborts if <path>/.git is directly a Git repository, opposed to a file refering to .git/modules/<name>. Aborts if repo <path> has local modifications, which includes having another current commit than in superrepo's index <path> entry. Note that the repository .git/modules/<name> is unaffected, so no objects are removed.

++git submodule init [<path>...]++ For the given <path>..., or if <path>... is not given, for all gitlinks (*to-do* only at toplevel?) in the index, map <path> to <name> using .gitmodule in the index, ensures an submodule.<name> section exists in .git/config, copies submodule.<name>.url from .gitmodule in the index if it doesn't already exist in .git/config, same for submodule.<name>.update. Aborts if for a gitlink the <path> does not exist in the index' .gitmodule. Note that it does not create .git/modules/<name> and it does not create <path>.

++git submodule update [--init] [<path>...]++ Without --init, aborts if submodule is not initialized (i.e. roughly, if .git/config has no submodule.<name> section; submodule.<name>.url seems not to be required, apparently it can use the one from .gitmodules, probably just the regular way the multiple Git config files work together). *to-so* does not care about untracked files lying around, does not modify files which are modified


++git rm <path>++. Note that it does not remove the respective section in .git/config.


++git status++ / ++git diff --submodule++ / ++git submodule status++. submodule status lists submodules (gitlinks in index and submodule.<path> section in .gitmodule of working tree) in the form "[+-]<commitid> <path> [(current-branch-or-commit)]". A "-" prefix means uninitialized, a " " or "+" means initialized, a "+" prefix means the submodule's current commit does not match the SHA1 of the superprojekts gitlink in the index. If the submodule is initialized but there is no "(current-branch-or-commit)" shown, that means the submodule does not yet have a repository (i.e. you need to do submodule update).


??? howto: 'add subrepo' resulting in deinitialized state, if I only want to add subrepo without working copy ???

??? howto: git rm <path> to really remove subrepository ??? Ignored files are lost

??? reset does not seem to affect ./git/modules/... ???

??? do all or only some commands abort if .gitmodules has unstaged modifications ???

??? AFAI the repository is in an invalid state if .gitmodules in the index does not match 1:1 with the gitlinks in the index. No, if that was so, the `git add <path>' where <path> is some git repository would not do what it does.  ???

=== submodule states

active:: submodule.<name>.active is true (e.g. in .git/config, not in .gitmodules), or submodule's path matches submodule.active, submodule.<name>.url is set, checked in this order. If submodule.<name>.active is set to false or submodule.active is set and excluedes submodule's path, submodule.<name>.url is ignored. (*to-do* orthogonal to registered/deinitialized?).

registered (*to-do* same as initialized?):: State after between submodule init and submodule deinit.

deinitialized (*to-do* same as unregistred?):: The index has the a gitlink entry for <path> and a .gitmodules entry, but in the working directory there's no <path> or it is an empty directory. For cases where you don't need the working tree of the subrepository, which is actually Git's default.

deleted:: .gitmodules no longer contains a submodule.<name> section, index has no <path> entry. However .git/modules/<name> still exists, so what we can checkout old commits which refer to the submodule at <path>.   ?? .git/config ???

never-existed / not yet existent:: As deleted, but .git/modules/<name> does not exists. *to-do* Also in .git/config, submodule.<locialname> does not exist, which it might for `improperly' deleted subrepositories.

??? what if at one point in time, <path> points to suberpository `foo', but at another time to a completely different subrepository `bar'? AFAIU, always the *current* .git/modules/<name> is used. *to-do* how to get to <name> - via .gitmodules in index?


==== Reference

- gitsubmodules(7): General info
- git-submodule(1): The git submodule commands
- gitmodules(5): The .gitmodules file, the config variables it can contain.
- https://git-scm.com/book/en/v2/Git-Tools-Submodules


== Maintenance

gitglossary(7) says `unreachble object' means `An object which is not reachable from a branch, tag, or any other reference.'. It also says `ref' means `A name that begins with refs/ ... There are a few special-purpose refs that do not begin with refs/. The most notable example is HEAD'. Thus apparently the term ref(erence) does not include reflogs.

== Talking to Mercurial

=== Bidirectional bridge

https://github.com/felipec/git-remote-hg


=== Migrate from Mercurial

https://github.com/frej/fast-export/


//  LocalWords:  pathspec
