:encoding: UTF-8
// The markup language of this document is AsciiDoc

= Photography

== White Balance

== Raw Images
- Contains minimally processed data from the image sensor 
- Raw image files are sometimes called digital negatives, as they fulfill the same role as negatives in film photography: that is, the negative is not directly usable as an image, but has all of the information needed to create an image. 
- Like a photographic negative, a raw digital image may have a wider dynamic range or color gamut than the eventual final image format, and it preserves most of the information of the captured image. 
- Raw image formats are intended to capture as closely as possible (i.e. at the best of the specific sensor's performance) the radiometric characteristics of the scene, that is, physical information about the light intensity and color of the scene.
- Raw files thus contain the full resolution (typically 12- or 14-bit) data as read out from each of the camera's image sensor pixels.
- To obtain an image from a raw file, this mosaic of data must be converted into standard RGB form. This is often referred to as "raw development". 
  - ?? Why cant this be a 1:1 trafo ??

- Nearly all digital cameras can process the image from the sensor into a JPEG file using settings for white balance, colour saturation, contrast, and sharpness that are either selected automatically or entered by the photographer before taking the picture. Cameras that produce raw files save these settings in the file, but defer the processing

== Lenses

- Test if the image quality of smaller/lighter/travelfriendly lenses really is not good enough for me. I buy a good camera also because of its features (AF, view fiender, ...), because I need those to enjoy making pictures without missing anything, not only because of its image quality.
- Focal length has more influence on DOF than aparture. With 2.8 and <70mm I can't get a decent bokeh anyway, so I can as well use 4 or even more? Mind also object distance. Larger COF at a given distance is more imortant than a shallow DOF?
- For hikes alone I don't need a shallow DOF.