:encoding: UTF-8
// The markup language of this document is AsciiDoc

= SQL

The most widely used relational query language. Standardized, however most systems add their own special constructs.

Trivia: Was originally designed to be a very simple small language.

== Intro

_SQL_ stands for structured query language. _RDBMS_ stands for Relational Database Management system.  A database most often contains one or more _tables_.  Each table is identified by a name.  Tables contain _records_ (rows) with data.

SQL is a DLS. Not turing complete. But being a constrained language, it is easier for the optimzer, since it's easier to determine whether a given optimization is safe. Especially parallizing is often rather easy.

SQL is close to the relational model, but not purely, for practical reasons. E.g. duplicate rows in a table are allowed. The relational model is all about sets where order doesn't matter, in practice one orders a lot in SQL. Differences regarding null values, set operations, .... Th

type conversions

- See chapter 5.5 Q27. Tables with one row and one column can be implicitely
  converted to scalar if needed.


== Type system

+CHAR(n)+ and +VARCHAR(n)+ are strings of up to n chars. The difference is
implementation-dependent. +BIT(n)+ and +BIT VARING(n)+ are analgous for bit
strings. +BOOLEAN+ can be one of +TRUE+, +FALSE+ or +UNKOWN+. +INT+ (or
+INTEGER+) and +SHORTINT+ are integers of implemenetation defined size. +FLOAT+
(or +REAL+) and +DOUBLE PRECISION+ are floating point numbers of implementation
defined size. +DECIMAL(n,d)+ are fixed-point numbers.


== Efficiency / Optimizations

Projection is relatively cheap. Join is relatively expensive. Join is obviously faster for fewer rows. But also for fewer columns, or fewer data in general, since more tuples fit into a page, and thus there's less page I/O.

For example, as an optimization, we want to 'push down projections': Do many projections as eary as possible, cut away every column you can and keep only those you must, having fewer data left for the next operators. Push down is in the sense that, assuming you have an projection as outermost operation keeping only one column, i.e. cutting away all the others, part of that can maybe done earlier.

There's even the field of 'column oriented databases' which store columns seperately. The idea being doing projections as early as possible and only work with as few data as possible.


== Joins

See also sql_joins in big_data.adoc. Recall that joins (except crossproduct), always have a condition. AFAIK ANSI SQL requires that an inner / outer JOIN has an ON part.

*to-do* It seems that the column names of the output tablen when using $$SELECT *$$ are implementation dependend. Some implementations only use the original column name, e.g. $$col1A$$, others prepend the table name like $$Table1.col1A$$.

_crossproduct_ (aka _cross join_): $$CROSS JOIN$$: However columns with same name are still removed *to-do* what if the values in these same named columns are different?

--------------------------------------------------
 Table1                   Table2
 col1A   col1B            col2A   col2B
 John    42               John    apples
 Bob     77               John    oranges
 Fred    3.14             Fred    bananas

 SELECT * FROM Table1 CROSS JOIN Table2
 col1A   col1B  col2A   col2B
 John    42     John    apples
 John    42     John    oranges
 John    42     Fred    bananas
 Bob     77     John    apples 
 Bob     77     John    oranges
 Bob     77     Fred    bananas
 Fred    3.14   John    apples 
 Fred    3.14   John    oranges
 Fred    3.14   Fred    bananas
--------------------------------------------------

_inner join_ (explicit syntax): $$INNER JOIN$$. E.g. $$SELECT * FROM Table1 INNER JOIN Table2 ON Table1.col1A = Table2.col2A;$$

_inner join_ (implicit syntax): $$FROM T1,T2 WHERE$$. E.g. $$SELECT * FROM Table1, Table2 WHERE Table1.col1A = Table2.col2A;$$. This implicit syntax  is no longer considered a best practice


== Other operations

for relational algebra, see relational_algebra in big_data.adoc.

SELECT: corresponds to projection in relational algebra

WHERE: corresponds to selection in relational algebra

GROUP BY: not part of the relational algebra

ORDER BY: not part of the relational algebra (*to-do* I am not 100% sure)


== Grammar / Syntax

See sql.yas
